**Hyperparameters Tuning**

1. GridSerchCV

2. RandomizedSerchCV

we will be working on the brest cancer dataset

Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

**Data collection & Processing**

In [2]:
# loding the data from sklearn
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

In [3]:
print(breast_cancer_dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]), 'frame': None, 'target_names': array(['malignant', 'benign'], dtype='<U9'), 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n', 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23'), 'filename': 'breast_cancer.csv', 'data_module': 'sklearn.datasets.data'}

In [4]:
# loding the data to a pandas dataframe

In [5]:
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

In [6]:
data_frame.head()

   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [7]:
# adding the 'target' column to our dataset
data_frame['label'] = breast_cancer_dataset.target

In [8]:
data_frame.tail()

     mean radius  mean texture  ...  worst fractal dimension  label
564        21.56         22.39  ...                  0.07115      0
565        20.13         28.25  ...                  0.06637      0
566        16.60         28.08  ...                  0.07820      0
567        20.60         29.33  ...                  0.12400      0
568         7.76         24.54  ...                  0.07039      1

[5 rows x 31 columns]

In [9]:
# number of rows and columns in daraset

data_frame.shape

(569, 31)

In [10]:
# getting some info about the dataset
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  label                    569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [11]:
# cheacking for missing values
data_frame.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [12]:
# statistical measure about the data
data_frame.describe()

       mean radius  mean texture  ...  worst fractal dimension       label
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [13]:
# cheaking  the distribution of the target value
data_frame['label'].value_counts()

label
1    357
0    212
Name: count, dtype: int64

1 --> Benign

0 --> Malignant

In [14]:
data_frame.groupby('label').mean()

       mean radius  mean texture  ...  worst symmetry  worst fractal dimension
label                             ...
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

# seprate the feature and Target

In [15]:
X = data_frame.drop(columns = 'label', axis = 1)
Y = data_frame['label']

In [16]:
print(X)

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [17]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: label, Length: 569, dtype: int64

In [19]:
X = np.asarray(X)
Y = np.asarray(Y)

# **GridserchCV**

GridserchCV is used for determining the best parameters for our model

In [20]:
# loading the svc model
model = SVC()

In [22]:
# Hyperparamaeters

parameters = {
    'kernel':['linear','poly','rbf','sigmoid'],
    'C':[1,5,10,20]
}

In [23]:
# grid serch

Classifier = GridSearchCV(model, parameters, cv=5)

In [24]:
# fitting the data to our model
Classifier.fit(X,Y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [25]:
Classifier.cv_results_

{'mean_fit_time': array([1.65487890e+00, 5.88817596e-03, 7.16595650e-03, 2.18775749e-02,
        3.19732828e+00, 4.13246155e-03, 4.24232483e-03, 1.37914181e-02,
        4.71879120e+00, 4.43840027e-03, 4.15577888e-03, 1.45337105e-02,
        9.69745941e+00, 4.83126640e-03, 4.45680618e-03, 1.65881634e-02]),
 'std_fit_time': array([5.32805317e-01, 2.14385233e-04, 2.96042398e-04, 5.58437296e-04,
        8.86945204e-01, 4.18490975e-04, 1.76968564e-04, 5.19805665e-04,
        9.29121596e-01, 1.97719192e-04, 1.63902298e-04, 1.79013989e-03,
        5.28831910e+00, 5.18192575e-04, 5.38233233e-04, 4.84681478e-03]),
 'mean_score_time': array([0.0014966 , 0.00206118, 0.00330606, 0.0057415 , 0.0012682 ,
        0.00131049, 0.0017827 , 0.00370703, 0.00129333, 0.00129561,
        0.00172358, 0.00376124, 0.0016995 , 0.00138526, 0.00171738,
        0.00448184]),
 'std_score_time': array([1.58225706e-04, 7.22217692e-05, 1.35073382e-04, 5.31228696e-05,
        4.25282611e-05, 2.41919562e-05, 1.34556603e-04, 7.49714188e-05,
        4.09998442e-05, 2.84637836e-05, 7.05784073e-05, 1.21383055e-04,
        4.59676026e-04, 2.13037075e-04, 2.02504011e-04, 1.11864608e-03]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'poly'},
  {'C': 5, 'kernel': 'rbf'},
  {'C': 5, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.94736842, 0.84210526, 0.85087719, 0.54385965, 0.94736842,
        0.88596491, 0.88596491, 0.49122807, 0.93859649, 0.88596491,
        0.87719298, 0.48245614, 0.92982456, 0.87719298, 0.87719298,
        0.47368421]),
 'split1_test_score': array([0.92982456, 0.88596491, 0.89473684, 0.45614035, 0.93859649,
        0.9122807 , 0.92982456, 0.42105263, 0.93859649, 0.92105263,
        0.92105263, 0.40350877, 0.95614035, 0.92105263, 0.92105263,
        0.40350877]),
 'split2_test_score': array([0.97368421, 0.92982456, 0.92982456, 0.46491228, 0.97368421,
        0.92105263, 0.93859649, 0.42105263, 0.97368421, 0.90350877,
        0.9122807 , 0.42105263, 0.95614035, 0.90350877, 0.92105263,
        0.42105263]),
 'split3_test_score': array([0.92105263, 0.94736842, 0.94736842, 0.38596491, 0.92982456,
        0.93859649, 0.94736842, 0.35087719, 0.94736842, 0.93859649,
        0.95614035, 0.34210526, 0.93859649, 0.93859649, 0.94736842,
        0.34210526]),
 'split4_test_score': array([0.95575221, 0.9380531 , 0.9380531 , 0.45132743, 0.96460177,
        0.95575221, 0.95575221, 0.37168142, 0.96460177, 0.95575221,
        0.94690265, 0.36283186, 0.96460177, 0.95575221, 0.9380531 ,
        0.3539823 ]),
 'mean_test_score': array([0.94553641, 0.90866325, 0.91217202, 0.46044093, 0.95081509,
        0.92272939, 0.93150132, 0.41117839, 0.95256948, 0.920975  ,
        0.92271386, 0.40239093, 0.9490607 , 0.91922062, 0.92094395,
        0.39886664]),
 'std_test_score': array([0.01868869, 0.03938232, 0.03544367, 0.05025317, 0.01621632,
        0.02368918, 0.02435811, 0.04857818, 0.01419963, 0.02470123,
        0.02787898, 0.0489065 , 0.01281637, 0.02730027, 0.02410455,
        0.0476401 ]),
 'rank_test_score': array([ 4, 12, 11, 13,  2,  6,  5, 14,  1,  8,  7, 15,  3, 10,  9, 16],
       dtype=int32)}

In [27]:
# best parameters

best_parameters = Classifier.best_params_
print(best_parameters)

{'C': 10, 'kernel': 'linear'}

In [28]:
# highest accuracy

highest_accuracy = Classifier.best_score_
print(highest_accuracy)

0.9525694767893185

In [26]:
# loding the results to a pandas dataframe
results = pd.DataFrame(Classifier.cv_results_)

In [29]:
results.head()

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       1.654879      0.532805  ...        0.018689                4
1       0.005888      0.000214  ...        0.039382               12
2       0.007166      0.000296  ...        0.035444               11
3       0.021878      0.000558  ...        0.050253               13
4       3.197328      0.886945  ...        0.016216                2

[5 rows x 15 columns]

In [30]:
grid_serch_results = results[['param_C','param_kernel','mean_test_score']]

In [34]:
grid_serch_results

    param_C param_kernel  mean_test_score
0         1       linear         0.945536
1         1         poly         0.908663
2         1          rbf         0.912172
3         1      sigmoid         0.460441
4         5       linear         0.950815
5         5         poly         0.922729
6         5          rbf         0.931501
7         5      sigmoid         0.411178
8        10       linear         0.952569
9        10         poly         0.920975
10       10          rbf         0.922714
11       10      sigmoid         0.402391
12       20       linear         0.949061
13       20         poly         0.919221
14       20          rbf         0.920944
15       20      sigmoid         0.398867

Highest accuracy = 95.2%

best paerameters = {'C': 10 , 'Kernal' = 'liner'}

# **RandomizedSerchCV**

In [35]:
# loading the svc model
model = SVC()

In [36]:
# Hyperparamaeters

parameters = {
    'kernel':['linear','poly','rbf','sigmoid'],
    'C':[1,5,10,20]
}

In [37]:
# grid serch

Classifier = RandomizedSearchCV(model, parameters, cv=5)

In [38]:
# fitting the data to our model
Classifier.fit(X,Y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [39]:
Classifier.cv_results_

{'mean_fit_time': array([1.73678350e+00, 4.40192223e-03, 3.97112122e+00, 4.94585037e-03,
        1.37413502e-02, 4.93083000e-03, 6.60047531e-03, 8.00000520e+00,
        4.66918945e-03, 1.37145996e-02]),
 'std_fit_time': array([7.32345387e-01, 6.65495931e-04, 7.96364015e-01, 2.02399406e-04,
        6.38125010e-04, 1.23438463e-03, 1.77629760e-03, 2.68800843e+00,
        2.10513372e-04, 5.91164497e-04]),
 'mean_score_time': array([0.00136127, 0.00139008, 0.0013936 , 0.0020083 , 0.00375214,
        0.00202231, 0.00210752, 0.00133333, 0.00129843, 0.00371122]),
 'std_score_time': array([4.34350232e-05, 1.18459115e-04, 1.95095253e-04, 6.37810652e-05,
        8.92699272e-05, 6.65411764e-04, 7.02048930e-04, 1.64096190e-04,
        2.17141611e-05, 9.60484271e-05]),
 'param_kernel': masked_array(data=['linear', 'poly', 'linear', 'rbf', 'sigmoid', 'rbf',
                    'poly', 'linear', 'poly', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[1, 5, 5, 1, 10, 20, 10, 20, 20, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 1},
  {'kernel': 'poly', 'C': 5},
  {'kernel': 'linear', 'C': 5},
  {'kernel': 'rbf', 'C': 1},
  {'kernel': 'sigmoid', 'C': 10},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'poly', 'C': 10},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'poly', 'C': 20},
  {'kernel': 'sigmoid', 'C': 5}],
 'split0_test_score': array([0.94736842, 0.88596491, 0.94736842, 0.85087719, 0.48245614,
        0.87719298, 0.88596491, 0.92982456, 0.87719298, 0.49122807]),
 'split1_test_score': array([0.92982456, 0.9122807 , 0.93859649, 0.89473684, 0.40350877,
        0.92105263, 0.92105263, 0.95614035, 0.92105263, 0.42105263]),
 'split2_test_score': array([0.97368421, 0.92105263, 0.97368421, 0.92982456, 0.42105263,
        0.92105263, 0.90350877, 0.95614035, 0.90350877, 0.42105263]),
 'split3_test_score': array([0.92105263, 0.93859649, 0.92982456, 0.94736842, 0.34210526,
        0.94736842, 0.93859649, 0.93859649, 0.93859649, 0.35087719]),
 'split4_test_score': array([0.95575221, 0.95575221, 0.96460177, 0.9380531 , 0.36283186,
        0.9380531 , 0.95575221, 0.96460177, 0.95575221, 0.37168142]),
 'mean_test_score': array([0.94553641, 0.92272939, 0.95081509, 0.91217202, 0.40239093,
        0.92094395, 0.920975  , 0.9490607 , 0.91922062, 0.41117839]),
 'std_test_score': array([0.01868869, 0.02368918, 0.01621632, 0.03544367, 0.0489065 ,
        0.02410455, 0.02470123, 0.01281637, 0.02730027, 0.04857818]),
 'rank_test_score': array([ 3,  4,  1,  8, 10,  6,  5,  2,  7,  9], dtype=int32)}

In [40]:
# best parameters

best_parameters = Classifier.best_params_
print(best_parameters)

{'kernel': 'linear', 'C': 5}

In [42]:
# highest accuracy

highest_accuracy = Classifier.best_score_
print(highest_accuracy)

0.9508150908244062

In [43]:
# loding the results to a pandas dataframe
results = pd.DataFrame(Classifier.cv_results_)

In [44]:
results.head()

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       1.736784      0.732345  ...        0.018689                3
1       0.004402      0.000665  ...        0.023689                4
2       3.971121      0.796364  ...        0.016216                1
3       0.004946      0.000202  ...        0.035444                8
4       0.013741      0.000638  ...        0.048906               10

[5 rows x 15 columns]

In [45]:
Randomized_serch_results = results[['param_C','param_kernel','mean_test_score']]

In [46]:
Randomized_serch_results

   param_C param_kernel  mean_test_score
0        1       linear         0.945536
1        5         poly         0.922729
2        5       linear         0.950815
3        1          rbf         0.912172
4       10      sigmoid         0.402391
5       20          rbf         0.920944
6       10         poly         0.920975
7       20       linear         0.949061
8       20         poly         0.919221
9        5      sigmoid         0.411178