**SVM Classifier**



Equation of the Hyperplane:

y = wx - b

**Gradient Descent:**



Gradient Descent is an optimization algorithm used for minimizing the loss function in various machine learning algorithms. It is used for
updating the parameters of the learning model.

W=W - a*dw

b = b - a*db

**Learning Rate:**


Learning rate is a tuning parameter in an optimization algorithm that determines the step size at each iteration while moving toward a
minimum of a loss function.

Support Vector Machine Classifier

In [155]:
#Importing the Dependencies
import numpy as np

class SVM_classifier():
  #initializing the hyperparameters
  def __init__(self, learning_rate, no_of_iterations, lambda_parameter):

    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations
    self.lambda_parameter = lambda_parameter

  # fitting the dataset to SVM Classifier
  def fit(self, X , Y):

    # m --> number of Data points --> numbers of rows
    # n --> number of input Feature --> numbers of columns
    self.m, self.n = X.shape

    # initiating weight Value and bias value
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y

    # implementing Gradient Descent algorithm for Optimization
    for i in range(self.no_of_iterations):
      self.update_weights()

  # Function for Updating The weight And bias value
  def update_weights(self):

    # lable encoding
    y_lable = np.where(self.Y <= 0, -1, 1)

    # Gradients (dw , db)
    for index, x_i in enumerate(self.X):

      condition = y_lable[index] * (np.dot(x_i, self.w) - self.b) >= 1

      if (condition == True):
        dw = 2 * self.lambda_parameter * self.w
        db = 0
      else:
        dw = 2 * self.lambda_parameter * self.w - np.dot(x_i, y_lable[index])
        db = y_lable[index]

      self.w = self.w - self.learning_rate * dw
      self.b = self.b - self.learning_rate * db

  #  predict the lable for a given input value
  def predict(self , X):
    output = np.dot(X, self.w) - self.b
    predicted_lable = np.sign(output)

    y_hat = np.where(predicted_lable <= -1, 0, 1)
    return y_hat

Importing the Dependencies

In [156]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

Data collecting and preprocessing

In [157]:
# loding the data from csv file to pandas dataframe
diabetes_data = pd.read_csv('/content/diabetes.csv')

In [158]:
diabetes_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [159]:
diabetes_data.shape

(768, 9)

In [160]:
diabetes_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [161]:
diabetes_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [162]:
diabetes_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [163]:
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0 --> non diabetic

1 --> diabetic

Splitting the feature and target

In [164]:
features = diabetes_data.drop(columns = 'Outcome', axis = 1)
target = diabetes_data['Outcome']

In [165]:
print(features)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [166]:
print(target)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Data standardization

In [167]:
scaler = StandardScaler()

In [168]:
scaler.fit(features)

StandardScaler()

In [169]:
standardized_data = scaler.transform(features)

In [170]:
features = standardized_data
target = diabetes_data['Outcome']

In [171]:
print(features)
print(target)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

Splitting the data into training and testing data

In [172]:
X_train , X_test , Y_train , Y_test = train_test_split(features, target, test_size = 0.2, random_state = 2)

In [173]:
print(features.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

Training the model

Suppoet Vector Machine Classifier

In [174]:
Classifier = SVM_classifier(learning_rate=0.001, no_of_iterations=1000, lambda_parameter=0.01)

In [175]:
# training the svm classifier with training data
Classifier.fit(X_train, Y_train)

model Evaluation

In [176]:
# accuracy on training data
X_train_prediction = Classifier.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

In [177]:
print('Accuracy score on training data : ', training_data_accuracy)

Accuracy score on training data :  0.7768729641693811

In [178]:
# accuracy on testing data
X_test_prediction = Classifier.predict(X_test)
testing_data_accuracy = accuracy_score(Y_test, X_test_prediction)

In [179]:
print('Accuracy score on testing data : ', testing_data_accuracy)

Accuracy score on testing data :  0.7532467532467533